apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: buurtzorg
spec:
  licenseKeySecret:
    name: iris-key-secret-dev
  configSource:
    name: buurtzorg-common-cpf-cm
  imagePullSecrets:
    - name: buurtzorg-pull-credentials
    - name: buurtzorg-intersystems-credentials
  volumes:
    # configmaps
    - name: buurtzorg-configmaps-cm
      configMap:
        name: buurtzorg-configmaps-cm
    - name: buurtzorg-defaultsettings-cm
      configMap:
        name: buurtzorg-defaultsettings-cm
    - name: buurtzorg-credentials-secret
      secret:
        secretName: buurtzorg-credentials-secret
  topology:
    data:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/iris:2024.2
      compatibilityVersion: '2024.2'
      # mirrored: true
      podTemplate:
        spec:
          nodeSelector:
            px/enabled: 'true'
          resources:
            requests:
              cpu: '1'
              memory: 512Mi
            limits:
              cpu: '2'
              memory: 2Gi
      irisDatabases:
        - name: BUURTZORG_DATA
          directory: /irissys/data/IRIS/mgr/BUURTZORG_DATA
          ecp: true
          # mirrored: true
        - name: BUURTZORG_CODE
          directory: /irissys/data/IRIS/mgr/BUURTZORG_CODE
      irisNamespaces:
        - name: BUURTZORG
          routines: BUURTZORG_CODE
          globals: BUURTZORG_DATA
          interop: true
      webgateway:
        image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/webgateway:2024.2
        replicas: 1
        loginSecret:
          name: webgateway-secret
        applicationPaths:
          # for accessing the mgmt portal of data
          - /csp
          - /csp/sys
          - /csp/bin
          - /csp/broker
          # for accessing the healthshare stuff
          - /csp/healthshare
          # vscode
          - /api
          - /api/atelier
        # this is needed for the sidecar web gateway, it is used in WG Server Access
        podTemplate:
          spec:
            resources:
              limits:
                cpu: 200m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 512Mi
            nodeSelector:
              px/enabled: 'true'
    compute:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/irishealth:2024.2
      # image: harbor.443916233c2349241f52.kpnappfactory.nl/hex/hex-buurtzorg:1.0.0-001
      compatibilityVersion: '2024.2'
      hpa:
        spec:
          minReplicas: 2
          maxReplicas: 3
          scaleTargetRef:
            kind: StatefulSet
            name: buurtzorg-compute
            apiVersion: apps/v1
      updateStrategy:
        type: RollingUpdate
      podTemplate:
        spec:
          # args:
          # - --up
          # - "false"
            # - --after iris session IRIS < /home/irisowner/after-install.script
          nodeSelector:
            px/enabled: 'true'
          resources:
            requests:
              cpu: '2'
              memory: 2Gi
            limits:
              cpu: '4'
              memory: 4Gi
      volumeMounts:
        - name: buurtzorg-configmaps-cm
          mountPath: /home/irisowner/configmaps
        - name: buurtzorg-defaultsettings-cm
          mountPath: /home/irisowner/sysdefaults
        - name: buurtzorg-credentials-secret
          readOnly: true
          mountPath: /home/irisowner/secrets
    webgateway:
      image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/webgateway:2024.2
      replicas: 1
      loginSecret:
        name: webgateway-secret
      applicationPaths:
        - /csp/sys
        - /csp/bin
        - /csp/broker
        - /csp/buurtzorg
      # vscode
        - /api
      # webterminal
        - /terminal
        - /terminal-vscode
        - /terminalsocket
      podTemplate:
        spec:
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
          nodeSelector:
            px/enabled: 'true'
    # arbiter:
    #   image: harbor.hex.kpnappfactory.nl/intersystems/intersystems/arbiter:2024.2
