apiVersion: v1
kind: ConfigMap
metadata:
  name: buurtzorg-configmaps-cm
  namespace: hex-buurtzorg-o
data:
  after-install.json: |
    {
      "namespace": "BUURTZORG",
      "certificatespath": "/home/irisowner/certificates",
      "systemdefaultspath": "/home/irisowner/sysdefaults",
      "system-mode": "BUURTZORG-DEVELOPMENT",
      "beheerapi": true,


      "monitoring": {
        "enabled": true,
        "stage": "dev",
        "description": "Buurtzorg",
        "customer": "Intern",
        "logstash-url": "https://monitor.itzosservices.nl/logstash",
        "logstash-ssl-config":  "Default",
        "logstash-check-server-identity":  false,
        "logstash-proxy-address": ""
      },
      "roles": [
      ],
      "webapplications": [
        {
          "url": "/buurtzorg/api/v1",
          "dispatchClass": "Buurtzorg.API.v1.disp",
          "role": "%All"
        }
      ],
      "cspapplications": [
        {
          "url": "/buurtzorg",
          "directory": "/tmp/src/csp/buurtzorg",
          "resource": "",
          "authenticationMethods": 64,
          "grant": "%All",
          "description": "",
          "cookiePath": "/buurtzorg/",
          "recurse": true,
          "autoCompile": true
        }
      ],
      "credentials": [
      ],
      "sqlconfigs": [
      ],
      "users": [
        {
            "name": "tstolker",
            "password": "defaultuser",
            "roles": "%ALL",
            "changePassword": true
        },
        {
            "name": "jplatenburg",
            "password": "defaultuser",
            "roles": "%ALL",
            "changePassword": true
        }
      ],
      "auditEvents": {
        "%System/%Login/Login": true,
        "%System/%Login/LoginFailure": true,
        "%System/%Login/Logout": true,
        "%System/%Login/LoginFailure": true,
        "%System/%Login/TaskEnd": true,
        "%System/%Login/TaskStart": true,
        "%System/%Login/Terminate": true,
        "%System/%Login/JobStart": true
      },
      "serviceregistries": [
      ],
      "backup-config": {
        "databases" : ["BUURTZORG_DATA"],
        "fullBackup": {
          "name": "Itzos Weekly",
          "folder": "/irissys/backups",
          "type": "full",
          "schema": {
              "type": "On Demand",
              "day": "tu",
              "time": "06:00:00"
          }
        }, 
        "cumulativeBackup": {
          "name": "Itzos Daily",
          "folder": "/irissys/backups",
          "type": "Cumulative",
          "schema": {
              "type": "On Demand",
              "day": "mo,we,th,fr",
              "time": "06:00:00"
          }
        }
      },
      "tasks": [
      ],
      "lookupTables": {
      },
      "remotedb": {
        "databasename": "REMOTE_DATABASE",
        "remoteserver": "IRIS-0",
        "directory": "/irissys/data/IRIS/mgr/BUURTZORG_DATA/",
        "globalmapping": [
          {
            "namespace": "BUURTZORG",
            "globalnames": [
              "%SYS.Log*"
              ]
          }
        ]
      },
      "production": "Buurtzorg.FoundationProduction"
    }
